version: '2'
services:
    jenkins:
        image: 'jenkins/jenkins:lts' 
        container_name: "jenkins"
        labels:
            kompose.service.type: nodeport
        ports:
            - '8080:8080'
            - '443:8443'
            - '50000:50000'
        volumes:
            - /home/tech/Bureau/jenkins:/jenkins_home
            - /home/tech/Bureau/jenkins:/var/jenkins_config
volumes:
    jenkins_data:
        driver: local
    jenkins:
        driver: local



